runtime: python
env: flex

entrypoint: gunicorn -b :$PORT -k flask_sockets.worker main:app

env_variables:
  CLOUDSQL_CONNECTION_NAME: ${{ secrets.instance_connection_name }}
  CLOUDSQL_USER: ${{ secrets.db_user }}
  CLOUDSQL_PASSWORD: ${{ secrets.db_password }}

beta_settings:
  cloud_sql_instances: ${{ secrets.instance_connection_name }}

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1