runtime: python
env: flex

entrypoint: gunicorn -b :$PORT -k flask_sockets.worker main:app

beta_settings:
  cloud_sql_instances: minichat-274103:asia-southeast1:minichat-database

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1