runtime: python
env: flex

entrypoint: gunicorn -b :$PORT -k flask_sockets.worker main:app

env_variables:
  CLOUDSQL_CONNECTION_NAME: ${INSTANCE_CONNECTION_NAME}
  CLOUDSQL_USER: ${DB_USER}
  CLOUDSQL_PASSWORD: ${DB_PASSWORD}

beta_settings:
  cloud_sql_instances: ${INSTANCE_CONNECTION_NAME}

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1